// frontend/AnimeCore/components/swiper/MainHero.tsx
import React, { useEffect, useState, useLayoutEffect } from 'react';
import {
    createStyles,
    Container,
    Title,
    Text,
    Space,
    Badge,
    Button,
    Skeleton,
} from '@mantine/core';
import { Navbar } from '../common/Navbar';
import { useMediaQuery } from '@mantine/hooks';
import * as voca from 'voca';

const useStyles = createStyles((theme) => ({
    root: {
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'black',
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        paddingTop: theme.spacing.xl * 2,
        paddingBottom: theme.spacing.xl * 2,
        minHeight: '90vh',
        boxShadow: `
            inset 0 4px 1800px rgb(7, 5, 25),
            inset 0 -40vh 140px 2px rgba(7, 5, 25, 0.9),
            inset 0 -15vh 140px 2px rgba(7, 5, 25, 0.7),
            inset 0 -5vh 140px 2px rgba(7, 5, 25, 0.4),
            inset 0 -2vh 140px 2px rgba(7, 5, 25, 0.2)`,

        [theme.fn.smallerThan('md')]: {
            minHeight: '30vh',
            maxHeight: '60vh',
            boxShadow: `
                inset 0px -30px 12px -2px rgba(7, 5, 25, 0.95),
                inset 0 -40vh 140px 2px rgba(7, 5, 25, 0.8),
                inset 0 -2vh 140px 2px rgba(7, 5, 25, 0.2)`,
        },
    },

    inner: {
        display: 'flex',

        [theme.fn.smallerThan('md')]: {
            flexDirection: 'column',
        },
    },

    image: {
        [theme.fn.smallerThan('md')]: {
            display: 'none',
        },
    },
    container: {
        marginTop: 'auto',
        marginLeft: 0,
        paddingLeft: theme.spacing.xl * 4,

        [theme.fn.smallerThan('md')]: {
            paddingLeft: theme.spacing.sm * 2,
            paddingRight: theme.spacing.sm * 2,
        },
    },
    content: {
        paddingTop: theme.spacing.xl * 2,
        paddingBottom: theme.spacing.xl * 2,
        marginRight: theme.spacing.xl * 3,

        [theme.fn.smallerThan('md')]: {
            marginRight: 0,
        },
    },

    title: {
        fontWeight: 900,
        lineHeight: 1.05,
        maxWidth: 500,
        fontSize: 48,
        display: 'flex',
        alignItems: 'center',

        [theme.fn.smallerThan('md')]: {
            maxWidth: '100%',
            fontSize: 34,
            lineHeight: 1.15,
        },
    },

    description: {
        color: theme.white,
        opacity: 0.75,
        maxWidth: 500,

        [theme.fn.smallerThan('md')]: {
            maxWidth: '100%',
        },
    },

    control: {
        paddingLeft: 50,
        paddingRight: 50,
        fontFamily: `Greycliff CF, ${theme.fontFamily}`,
        fontSize: 22,

        [theme.fn.smallerThan('md')]: {
            width: '100%',
        },
    },

    line: {
        color: theme.colors.yellow[6],
    },

    info: {
        ':after': {
            content: '" ▪ "',
        },
    },
    buttonContainer: {
        display: 'flex',
    },
    tagContainer: {
        [theme.fn.smallerThan('md')]: {
            display: 'none',
        },
    },
    infoContainer: {
        [theme.fn.smallerThan('md')]: {
            display: 'none',
        },
    },
}));

export const MainHero = ({ backgroundImage = '', backgroundBanner = '' }) => {
    const { classes } = useStyles();
    const [animeSummaryContent, setAnimeSummaryContent] = useState('');
    const [heroBackgroundImage, setHeroBackgroundImage] = useState('');

    const mobile = useMediaQuery('(min-width: 0px) and (max-width: 576px)');
    const tablet = useMediaQuery('(min-width: 577px) and (max-width: 768px)');
    const fullhd = useMediaQuery('(min-width: 769px) and (max-width: 992px)');

    // Props please replace me
    const animeTitle = 'Hyouka';
    const animeSummary = `High school freshman Houtarou Oreki has but one goal: to lead a gray life while conserving as much energy as he can. Unfortunately, his peaceful days come to an end when his older sister, Tomoe, forces him to save the memberless Classics Club from disbandment. Luckily, Oreki's predicament seems to be over when he heads to the clubroom and discovers that his fellow first-year, Eru Chitanda, has already become a member. However, despite his obligation being fulfilled, Oreki finds himself entangled by Chitanda's curious and bubbly personality, soon joining the club of his own volition. Hyouka follows the four members of the Classics Club—including Oreki's friends Satoshi Fukube and Mayaka Ibara—as they, driven by Chitanda's insatiable curiosity, solve the trivial yet intriguing mysteries that permeate their daily lives.`;

    useEffect(() => {
        if (mobile) {
            setAnimeSummaryContent(voca.truncate(animeSummary, 200)); // 200 words max
            setHeroBackgroundImage(backgroundBanner);
        } else if (tablet) {
            setAnimeSummaryContent(voca.truncate(animeSummary, 350)); // 350 words max
            setHeroBackgroundImage(backgroundImage);
        } else if (fullhd) {
            setAnimeSummaryContent(voca.truncate(animeSummary, 500)); // 500 words max
            setHeroBackgroundImage(backgroundImage);
        } else {
            setAnimeSummaryContent(voca.truncate(animeSummary, 500)); // This is the normal one
            setHeroBackgroundImage(backgroundImage); // This is the normal one
        }
    }, [fullhd, tablet, mobile, backgroundBanner, backgroundImage]);

    const [isLoading, setIsLoading] = useState(true);

    setTimeout(() => {
        if (isLoading) {
            setIsLoading(false);
        }
    }, 2000);

    return (
        <div
            className={classes.root}
            style={{
                backgroundImage: `url('${heroBackgroundImage}')`,
            }}
        >
            <Navbar />

            <Container size="lg" className={classes.container}>
                <div className={classes.inner}>
                    <div className={classes.content}>
                        <Title className={classes.title}>
                            {isLoading ? (
                                <>
                                    <Skeleton
                                        height={20}
                                        width={120}
                                    ></Skeleton>
                                </>
                            ) : (
                                <>
                                    <Text
                                        component="span"
                                        size="xl"
                                        weight="bold"
                                        color="yellow"
                                        sx={(theme) => ({
                                            [theme.fn.smallerThan('sm')]: {
                                                fontSize: theme.fontSizes.sm,
                                            },
                                        })}
                                    >
                                        Featured
                                    </Text>
                                </>
                            )}

                            <Space w="sm" />
                            {isLoading ? (
                                <>
                                    <Skeleton height={20} width={60}></Skeleton>
                                </>
                            ) : (
                                <>
                                    <div
                                        className={classes.line}
                                        style={{
                                            display: 'inline-block',
                                            width: '60px',
                                            borderTop: '4px solid',
                                            borderRadius: 10,
                                        }}
                                    />
                                </>
                            )}
                        </Title>
                        <Title order={1}>
                            {isLoading ? (
                                <>
                                    <Skeleton mt="lg" width={180} height={50} />
                                </>
                            ) : (
                                <>
                                    <Text
                                        size="lg"
                                        color="white"
                                        inherit
                                        sx={(theme) => ({
                                            [theme.fn.smallerThan('sm')]: {
                                                fontSize: 30, // Fix Me
                                            },
                                        })}
                                    >
                                        {animeTitle}
                                    </Text>
                                </>
                            )}
                        </Title>
                        <Title className={classes.infoContainer}>
                            {isLoading ? (
                                <>
                                    <Skeleton mt="lg" width={270} height={20} />
                                </>
                            ) : (
                                <>
                                    <Text
                                        className={classes.info}
                                        component="span"
                                        color="white"
                                    >
                                        TV
                                    </Text>
                                    <Text
                                        className={classes.info}
                                        component="span"
                                        color="white"
                                    >
                                        22 eps
                                    </Text>
                                    <Text
                                        className={classes.info}
                                        component="span"
                                        color="white"
                                    >
                                        Completed
                                    </Text>
                                    <Text
                                        className={classes.info}
                                        component="span"
                                        color="white"
                                    >
                                        Spring 2012
                                    </Text>
                                    <Text component="span" color="white">
                                        Kyoto Animations
                                    </Text>
                                </>
                            )}
                        </Title>
                        <Space h="md" />
                        <>
                            {isLoading ? (
                                <>
                                    <Skeleton
                                        mt="sm"
                                        width="60vw"
                                        height={60}
                                    />
                                </>
                            ) : (
                                <>
                                    <Text color="gray">
                                        {animeSummaryContent}
                                    </Text>
                                </>
                            )}
                        </>
                        <Space h="xl" />
                        <div className={classes.tagContainer}>
                            {isLoading ? (
                                <>
                                    <Skeleton height={24} width="50vw" />
                                </>
                            ) : (
                                <>
                                    <Badge
                                        component="span"
                                        size="lg"
                                        radius="sm"
                                        variant="filled"
                                        mr="md"
                                        sx={(theme) => ({
                                            backgroundColor:
                                                theme.colors.blue[9],
                                        })}
                                    >
                                        Mystery
                                    </Badge>
                                    <Badge
                                        component="span"
                                        size="lg"
                                        radius="sm"
                                        variant="filled"
                                        mr="md"
                                        sx={(theme) => ({
                                            backgroundColor:
                                                theme.colors.blue[9],
                                        })}
                                    >
                                        Slice of Life
                                    </Badge>
                                </>
                            )}
                        </div>
                        <Space h="xl" />
                        <div className={classes.buttonContainer}>
                            {isLoading ? (
                                <>
                                    <Skeleton width="60px" />
                                </>
                            ) : (
                                <>
                                    <Button
                                        color="yellow"
                                        sx={(theme) => ({
                                            backgroundColor:
                                                theme.colors.yellow[9],
                                            height: 60,

                                            [theme.fn.largerThan('sm')]: {
                                                width: 60,
                                            },
                                        })}
                                        radius="lg"
                                    >
                                        <img
                                            src="/icons/play.svg"
                                            width={24}
                                            height={24}
                                        />
                                        <Text color="dark" weight={700}>
                                            Watch
                                        </Text>
                                    </Button>
                                </>
                            )}
                            {isLoading ? (
                                <>
                                    <Skeleton ml="xl" height={60} width={120} />
                                </>
                            ) : (
                                <>
                                    <Button
                                        ml="xl"
                                        color="yellow"
                                        variant="outline"
                                        sx={(theme) => ({
                                            borderWidth: 4,
                                            height: 60,
                                            borderColor: theme.colors.yellow[9],
                                        })}
                                        radius="lg"
                                        rightIcon={
                                            <img src="/icons/chevrons-right.svg" />
                                        }
                                    >
                                        <Text
                                            weight={700}
                                            size="lg"
                                            color="yellow"
                                        >
                                            Details
                                        </Text>
                                    </Button>
                                </>
                            )}
                        </div>
                    </div>
                </div>
            </Container>
        </div>
    );
};

// frontend/AnimeCore/src/lib/components/swiper/MainHero.svelte
<script lang="ts">
    import { SwiperSlide } from "swiper/svelte";
    
    import Navbar from "$components/common/Navbar.svelte";
    import { truncateString } from "$lib/functions/truncateText";
    import { responsiveMode } from "$store/responsive";

    export let backgroundImageUrl: string;
    export let animeName: string;
    export let backgroundBannerUrl = "https://media.kitsu.io/anime/poster_images/6686/large.jpg";
    export let animeSummary = `High school freshman Houtarou Oreki has but one goal: to lead a gray life while conserving as much energy as he can. Unfortunately, his peaceful days come to an end when his older sister, Tomoe, forces him to save the memberless Classics Club from disbandment. Luckily, Oreki's predicament seems to be over when he heads to the clubroom and discovers that his fellow first-year, Eru Chitanda, has already become a member. However, despite his obligation being fulfilled, Oreki finds himself entangled by Chitanda's curious and bubbly personality, soon joining the club of his own volition. Hyouka follows the four members of the Classics Club—including Oreki's friends Satoshi Fukube and Mayaka Ibara—as they, driven by Chitanda's insatiable curiosity, solve the trivial yet intriguing mysteries that permeate their daily lives.`;

    let wordCount: number;

    $: {
        switch ($responsiveMode) {
            case "mobile":
                wordCount = 100;
                break;
            case "tablet":
                wordCount = 350;
                break;

            case "desktop":
            case "widescreen":
            case "fullhd":
                wordCount = 500;
                break;
            default:
                break;
        }
    }
</script>

<SwiperSlide>
    <section
        class="hero {$responsiveMode === 'mobile'
            ? 'is-halfheight mobile-shadow'
            : 'is-fullheight desktop-shadow'}"
        style="
            background-image: url({$responsiveMode === 'mobile'
            ? backgroundBannerUrl
            : backgroundImageUrl});
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
        "
    >
        <!-- Hero head: will stick at the top -->
        <div class="hero-head">
            <Navbar />
        </div>

        <!-- Hero content: will be in the middle -->
        <div class="hero-body is-align-items-self-end">
            <div class="container pb-6">
                <div
                    class="title has-text-warning  container {$responsiveMode === 'mobile'
                        ? 'is-size-7 mb-0'
                        : 'is-size-4'}"
                >
                    <div class="is-flex">
                        <span class="pr-2 is-align-self-center">Featured</span>
                        <div
                            class="is-align-self-center"
                            style="display: inline-block;width: 4em;border-top: 6px solid;"
                        />
                    </div>
                </div>
                <div
                    class="title has-text-white is-bold {$responsiveMode === 'mobile'
                        ? 'is-size-2 mb-0'
                        : 'is-size-1'}"
                >
                    {animeName}
                </div>
                <div
                    class="subtitle has-text-white pt-5 {$responsiveMode === 'mobile'
                        ? 'is-size-7'
                        : 'is-size-6'}"
                    style={$responsiveMode === "mobile" ? "width: 100%;" : "width: 70%;"}
                >
                    {truncateString(animeSummary, wordCount)}
                </div>
                <!-- Tags -->
                <div class="subtitle is-hidden-mobile">
                    <span class="tag is-size-6 mx-1 is-bold is-black"> Mystery </span>
                    <span class="tag is-size-6 mx-1 is-bold is-black"> Slice of Life </span>
                </div>

                <div class="buttons {$responsiveMode === 'mobile' ? 'are-small' : 'are-medium'}">
                    <button
                        class="button is-warning has-border-transparent mx-3"
                        style="border-radius: 12px"
                    >
                        <img alt="" src="/icons/play.svg" />
                        <span class="has-text-weight-bold is-size-6 is-hidden-desktop mx-1"
                            >Watch</span
                        >
                    </button>
                    <button class="button is-warning is-outlined mx-4 is-flex">
                        <span class="has-text-weight-semibold mx-1">Details</span>
                        <img
                            class="is-align-self-flex-center"
                            alt=""
                            src="/icons/chevrons-right.svg"
                        />
                    </button>
                    <button
                        class="button has-border-warning-light is-warning is-outlined mx-4 is-hidden-mobile mainhero__previous__el"
                    >
                        <span class="icon is-small">
                            <img alt="" src="/icons/chevron-left.svg" height={24} width={24} />
                        </span>
                    </button>
                    <button
                        class="button has-border-warning-light is-warning is-outlined mx-1 is-hidden-mobile mainhero__next__el"
                    >
                        <span class="icon is-small">
                            <img alt="" src="/icons/chevron-right.svg" height={24} width={24} />
                        </span>
                    </button>
                </div>
            </div>
        </div>

        <!-- Hero footer: will stick at the bottom -->
        <div class="hero-foot is-hidden-mobile">
            <nav class="tabs is-clipped">
                <div class="container has-text-white">
                    <div class="columns is-mobile is-centered">
                        <div class="column is-narrow px-1">
                            <img src="/icons/arrow-down.svg" alt="" height={24} width={24} />
                        </div>
                        <div class="column is-narrow px-1">scroll below</div>
                    </div>
                </div>
            </nav>
        </div>
    </section>
</SwiperSlide>

<style lang="scss">
    .button {
        border-radius: 16px !important;
        border-width: 5px;

        @media screen and (max-width: 768px) {
            border-width: 3px;
            border-radius: 8px !important;
        }
    }
    .desktop-shadow {
        box-shadow: inset 0 4px 1800px rgb(7, 5, 25), inset 0 -40vh 140px 2px rgba(7, 5, 25, 0.9),
            inset 0 -15vh 140px 2px rgba(7, 5, 25, 0.7), inset 0 -5vh 140px 2px rgba(7, 5, 25, 0.4),
            inset 0 -2vh 140px 2px rgba(7, 5, 25, 0.2);
    }
    .mobile-shadow {
        box-shadow: inset 0px -30px 12px -2px rgba(7, 5, 25, 0.95),
            inset 0 -40vh 140px 2px rgba(7, 5, 25, 0.8), inset 0 -2vh 140px 2px rgba(7, 5, 25, 0.2);
    }
</style>
