// frontend/AnimeCore/components/Genre/Slide.tsx
import {
    Badge,
    Container,
    createStyles,
    Divider,
    Group,
    Input,
    SimpleGrid,
    Text,
    Title,
    useMantineTheme,
} from '@mantine/core';
import { memo } from 'react';

const useStyles = createStyles((theme) => ({
    root: {
        minHeight: '100vh',

        [theme.fn.smallerThan('md')]: {
            display: 'none',
        },
    },

    wrapper: {
        paddingTop: 30,
        paddingLeft: theme.spacing.xl * 4,
        paddingRight: theme.spacing.xl * 4,

        [theme.fn.smallerThan('md')]: {
            paddingLeft: theme.spacing.sm * 2,
            paddingRight: theme.spacing.sm * 2,
        },
    },

    inner: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },

    dots: {
        position: 'absolute',
        color:
            theme.colorScheme === 'dark'
                ? theme.colors.dark[5]
                : theme.colors.gray[1],

        '@media (max-width: 755px)': {
            display: 'none',
        },
    },

    dotsLeft: {
        left: 0,
        top: 0,
    },

    title: {
        textAlign: 'center',
        fontWeight: 800,
        fontSize: 40,
        letterSpacing: -1,
        color: theme.colorScheme === 'dark' ? theme.white : theme.black,
        marginBottom: theme.spacing.xs,
        fontFamily: `Greycliff CF, ${theme.fontFamily}`,

        '@media (max-width: 520px)': {
            fontSize: 28,
            textAlign: 'left',
        },
    },

    description: {
        textAlign: 'center',

        '@media (max-width: 520px)': {
            textAlign: 'left',
            fontSize: theme.fontSizes.md,
        },
    },

    controls: {
        marginTop: theme.spacing.lg,
        display: 'flex',
        justifyContent: 'center',

        '@media (max-width: 520px)': {
            flexDirection: 'column',
        },
    },

    control: {
        '&:not(:first-of-type)': {
            marginLeft: theme.spacing.md,
        },

        '@media (max-width: 520px)': {
            height: 42,
            fontSize: theme.fontSizes.md,

            '&:not(:first-of-type)': {
                marginTop: theme.spacing.md,
                marginLeft: 0,
            },
        },
    },
    badges: {
        cursor: 'pointer',
        textTransform: 'capitalize',
        height: 45,
    },
}));

const GenreSlide = memo(function GenreSlider() {
    const { classes } = useStyles();
    const theme = useMantineTheme();

    const badgeData = [
        { name: 'Action', color: theme.colors.blue[4] },
        { name: 'Adventure', color: theme.colors.red[4] },
        { name: 'Comedy', color: theme.colors.yellow[6] },
        { name: 'Drama', color: theme.colors.green[5] },
        { name: 'Ecchi', color: theme.colors.green[5] },
        { name: 'Fantasy', color: theme.colors.blue[4] },
        { name: 'Horror', color: theme.colors.red[4] },
        { name: 'Mahou Shoujo', color: theme.colors.red[3] },
        { name: 'Mecha', color: theme.colors.orange[3] },
        { name: 'Music', color: theme.colors.cyan[5] },
        { name: 'Mystery', color: theme.colors.yellow[5] },
        { name: 'Psychological', color: theme.colors.red[6] },
        { name: 'Romance', color: theme.colors.red[5] },
        { name: 'Sci-Fi', color: theme.colors.green[5] },
        { name: 'Slice of Life', color: theme.colors.yellow[5] },
        { name: 'Sports', color: theme.colors.red[8] },
        { name: 'Supernatural', color: theme.colors.cyan[8] },
        { name: 'Thriller', color: theme.colors.green[5] },
    ];

    return (
        <div
            className={classes.root}
            style={{ backgroundColor: theme.colors.blue[9] }}
        >
            <Container className={classes.wrapper} size={1400}>
                <div className={classes.inner}>
                    <Input
                        width={600}
                        styles={{
                            wrapper: {
                                width: '80vh',
                            },
                            input: {
                                height: 80,
                                borderRadius: 14,
                                borderColor: '#FF7081',
                                borderWidth: 4,
                                alignSelf: 'center',
                                backgroundColor: 'white',
                                color: theme.black,
                            },
                        }}
                        icon={
                            <img
                                src="/icons/search-red.svg"
                                alt=""
                                height={36}
                                width={36}
                            />
                        }
                        variant="unstyled"
                        placeholder="Search for anything"
                        radius="lg"
                        size="xl"
                    />

                    <Divider
                        mt={50}
                        label={<Text size="sm">or search by genres</Text>}
                        labelPosition="center"
                        size="md"
                        sx={{ width: 300 }}
                    />
                    <SimpleGrid
                        mt="xl"
                        cols={6}
                        spacing={40}
                        sx={{ justifyItems: 'center' }}
                    >
                        {badgeData.map((item, index) => {
                            return (
                                <Badge
                                    key={index}
                                    className={classes.badges}
                                    size="xl"
                                    style={{
                                        backgroundColor: item.color,
                                    }}
                                    variant="filled"
                                    radius="md"
                                >
                                    <Text color={theme.black}>{item.name}</Text>
                                </Badge>
                            );
                        })}
                    </SimpleGrid>
                    <Title mt={100} order={3}>
                        Choose your preferences
                    </Title>
                    <Text align="center" sx={{ maxWidth: 528 }}>
                        Choose some options to customize your experience. You
                        can change them anytime by clicking the profile icon and
                        going to Settings
                    </Text>
                    <Group mt="lg">
                        <Text>
                            Romaji Naming{' '}
                            <img
                                src="/icons/chevron-down.svg"
                                alt=""
                                width={30}
                                height={30}
                            />
                        </Text>
                        <Divider
                            sx={{ height: 50 }}
                            size="sm"
                            orientation="vertical"
                        />
                        <Text>
                            10 point scoring system{' '}
                            <img
                                src="/icons/chevron-down.svg"
                                alt=""
                                width={30}
                                height={30}
                            />
                        </Text>
                        <Divider
                            sx={{ height: 50 }}
                            size="sm"
                            orientation="vertical"
                        />
                        <Text>
                            2 trackers added{' '}
                            <img
                                src="/icons/chevron-down.svg"
                                alt=""
                                width={30}
                                height={30}
                            />
                        </Text>
                        <Divider
                            sx={{ height: 50 }}
                            size="sm"
                            orientation="vertical"
                        />
                        <Text>
                            Show 18+ content{' '}
                            <img
                                src="/icons/chevron-down.svg"
                                alt=""
                                width={30}
                                height={30}
                            />
                        </Text>
                    </Group>
                </div>
            </Container>
        </div>
    );
});

export default GenreSlide;

// frontend/AnimeCore/src/lib/components/Genre/Slide.svelte
<script lang="ts">
    import AutoComplete from "$components/Genre/AutoComplete.svelte";
    import ChevronDown from "$icons/Chevron-Down.svelte";
    import ChevronUpDown from "$icons/Chevron-Up-Down.svelte";

    const badgeData = [
        { name: "Action", class: "bg-indigo-700 hover:bg-indigo-900" },
        { name: "Adventure", class: "bg-red-500 hover:bg-red-700" },
        { name: "Comedy", class: "bg-amber-300 hover:bg-amber-500" },
        { name: "Drama", class: "bg-green-500 hover:bg-green-700" },
        { name: "Ecchi", class: "bg-green-400 hover:bg-green-600" },
        { name: "Fantasy", class: "bg-indigo-400 hover:bg-indigo-600" },
        { name: "Horror", class: "bg-red-400 hover:bg-red-600" },
        { name: "Mahou Shoujo", class: "bg-red-300 hover:bg-red-500" },
        { name: "Mecha", class: "bg-orange-300 hover:bg-orange-500" },
        { name: "Music", class: "bg-cyan-500 hover:bg-cyan-700" },
        { name: "Mystery", class: "bg-amber-300 hover:bg-amber-500" },
        { name: "Psychological", class: "bg-red-500 hover:bg-red-700" },
        { name: "Romance", class: "bg-red-300 hover:bg-red-500" },
        { name: "Sci-Fi", class: "bg-green-400 hover:bg-green-600" },
        { name: "Slice of Life", class: "bg-amber-300 hover:bg-amber-500" },
        { name: "Sports", class: "bg-red-500 hover:bg-red-700" },
        { name: "Supernatural", class: "bg-cyan-500 hover:bg-cyan-700" },
        { name: "Thriller", class: "bg-green-400 hover:bg-green-600" }
    ];
</script>

<div class="hero min-h-[20vh] md:min-h-screen bg-base-100">
    <div class="hero-content text-center p-0">
        <div>
            <AutoComplete />
            <!-- Mobile Version  -->
            <div class="block md:hidden">
                <div class="dropdown mt-5">
                    <div tabindex="0" class="m-1 btn normal-case">
                        or search by genres <ChevronUpDown color="#D8D8D8" height={18} width={18} />
                    </div>
                    <ul
                        tabindex="0"
                        class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52 items-center inset-x-0 mx-auto pt-6"
                    >
                        {#each badgeData as item}
                            <li>{item.name}</li>
                        {/each}
                    </ul>
                </div>
            </div>
            <!-- Desktop Version -->
            <div class="hidden md:block">
                <div class="divider w-80 mx-auto mt-12 mb-6 before:bg-white after:bg-white" >or search by genres</div>
                <div class="grid grid-cols-6 gap-x-10 gap-y-5 justify-items-center">
                    {#each badgeData as item}
                        <div class="btn font-bold text-black w-fit whitespace-nowrap {item.class}">
                            {item.name}
                        </div>
                    {/each}
                </div>
                <div class="mt-24 flex flex-col items-center">
                    <div class="w-[500px]">
                        <h1 class="font-bold text-3xl mb-2 text-white">Choose your preferences</h1>
                        <p>
                            Choose some options to customize your experience. You can change them
                            anytime by clicking the profile icon and going to Settings
                        </p>
                    </div>
                </div>
                <div class="flex flex-col w-full lg:flex-row justify-center mt-8 text-white">
                    <div class="flex flex-row align-center">
                        Romaji Naming <ChevronDown height={30} width={30} />
                    </div>
                    <div class="divider lg:divider-horizontal before:bg-white after:bg-white" />
                    <div class="flex flex-row align-center">
                        10 point scoring system <ChevronDown height={30} width={30} />
                    </div>
                    <div class="divider lg:divider-horizontal before:bg-white after:bg-white" />
                    <div class="flex flex-row align-center">
                        2 trackers added <ChevronDown height={30} width={30} />
                    </div>
                    <div class="divider lg:divider-horizontal before:bg-white after:bg-white" />
                    <div class="flex flex-row align-center">
                        Show 18+ content <ChevronDown height={30} width={30} />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
